version: '2'
services:
  api:
    image: email_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SENDGRID_API_KEY: ""
      SES_REGION: ""
      SES_ACCESS_KEY_ID: ""
      SES_SECRET_ACCESS_KEY: ""
    ports:
    - 127.0.0.1:80:80
    volumes:
    - ./smacc_email:/app/smacc_email:ro
    - ./common:/app/common:ro
